# Generated by Django 3.2.3 on 2021-07-08 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Pais')),
                ('nombrePais', models.CharField(max_length=50, verbose_name='Nombre del Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Usario')),
                ('telefono', models.CharField(max_length=12, verbose_name='telefono')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('constraseña', models.CharField(max_length=50, verbose_name='Constraseña')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
    ]
