# Generated by Django 3.2.3 on 2021-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Usario')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('constraseña', models.CharField(max_length=50, verbose_name='Constraseña')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
            ],
        ),
    ]
